---
title: "Session 8: Hands-on activity #4"
format: revealjs
metadata-files:
  - _slides.yml
  - ../../_metadata.yml
---

# Housekeeping


# Session overview


## 🎯 Learning Objectives

By the end of this session, students will be able to:

> - Search for window-based collocations and n-grams in AntConc 
> - Calculate commonly used strengths of association measures by hand using spreadsheet software
> - Discuss benefits and drawbacks of different strength of association measures

---

# Generating N-gram list with AntConc

- Let's generate two list of n-grams.
- You can use either English or Japanese. 
  
- For Japanese you can use `Aozora 1000` data we used.
- For English you can use `Aozora 1000` data we used.


# Generating P-frame list with AntConc

- Let's now generate p-frame.
- You can use either English or Japanese. When using Japanese you can use `Aozora 1000` data we used.



# Searching collocations on AntConc

## Recap: What is collocation?

- Collocation 

## Collocation in AntConc

- explain



# Calculating Strengths of Association (SOA) measures

## Calculating SOA by hand

- Open Google Sreadsheet.
- Build function to calculate the following SOA measures
  - T-score
  - Mutual Information
  - Mutual Information Squared ($MI^2$)
  - LogDice


## Understanding collocational characteristics by plotting

- Let's make plots based on the calculated 

- Plot 1: 
  - X-Axis: T-score
  - Y-Axis: MI
- Plot 2:
  - X-Axis: LogDice
  - Y-Axis: MI


## Discussion: Describe the characteristics of each index

- What are the characteristics of SOA indices?
  - T-score
  - MI
  - LogDice


## (Advanced) how can I generate a collocation list?

- Colab notebook



---

# Hands-on Activity


# Reflection

- You can now do the followings:
  - Generate lists of n-grams using AntConc.
  - Search for collocates with AntConc.
  - Calculate major Strengths of Association (SOA) measures by hand.


# Next step